# Generated by Django 6.0 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
