# Generated by Django 6.0 on 2026-03-10 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_for_areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
